pull_request_rules:
  - name: Automatic merge dependabot PR
    conditions:
      - and:
          - author~=^dependabot(|-preview)\[bot\]$
          - check-success=continuous-integration
    actions:
      merge:
        method: squash
