generation: 1
sets:
  # Makes everything but install files
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: false
        name: install
    dimensions:
      os:
        - Ubuntu Focal
        - Ubuntu Jammy # comment in for tier 2
        - macOS 11 (Big Sur)
        - Windows 10 # comment in for tier 3
      buildType:
        - Binary
        - Source
  #####################
  # INSTALL FROM SOURCE
  #####################
  # Install on MacOS from source
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: osx
      - isMatch: true
        name: src
    dimensions:
      os:
        - macOS 11 (Big Sur)
      buildType:
        - Source
  # Install on Windows from source
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: windows
      - isMatch: true
        name: src
    dimensions:
      os:
        - Windows 10
      buildType:
        - Source
  # Install on Ubuntu from source
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: ubuntu
      - isMatch: true
        name: src
    dimensions:
      os:
        - Ubuntu Focal
        - Ubuntu Jammy
      buildType:
        - Source
  #####################
  # INSTALL FROM BINARIES
  #####################
  # Install on MacOS from binaries
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: osx
      - isMatch: false
        name: src
    dimensions:
      os:
        - macOS 11 (Big Sur)
      buildType:
        - Binary
  # Install on Windows from binaries
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: windows
      - isMatch: false
        name: src
    dimensions:
      os:
        - Windows 10
      buildType:
        - Binary
  # Install on Ubuntu from binaries
  - filters:
      - isMatch: true
        labels:
          - garden
      - isMatch: true
        name: ubuntu
      - isMatch: false
        name: src
    dimensions:
      os:
        - Ubuntu Focal
        - Ubuntu Jammy
      buildType:
        - Binary
