generation: 1
sets:
  # Documentation
  # This is only being run on one combination since this is testing the documentation
  # and the functionality seen in the documentation will be tested on several other
  # platforms, chip sets, and operating systems in the core and feature test cases
  - filters:
      - isMatch: true
        labels:
          - Garden
          # - General tutorials
    dimensions:
      os:
        - Ubuntu Bionic - debs
        - Ubuntu Focal - debs
